spring.application.name=BuraczydloBackend

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server Configuration
server.port=${SERVER_PORT:8080}

# Security Configuration (for development)
# spring.security.user.name=admin
# spring.security.user.password=admin

# Session Configuration
spring.session.store-type=none
spring.session.timeout=86400
logging.level.org.springframework.security=DEBUG
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None

# Spotify API Configuration
spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}
spotify.redirect.uri=${SPOTIFY_REDIRECT_URI}