apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:            
    app: backend 
spec:
  containers:
  - name: backend
    image: buraczydlo-backend:latest
    imagePullPolicy: Never
    envFrom:
    - secretRef:
        name: db-secret
    ports: 
    - containerPort: 8080