server {
    listen 80;

    # 1. Serwowanie Frontendu (React)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. REVERSE PROXY dla Backend-u
    location /api/ {
        # 'backend' to nazwa usługi z Twojego compose.yaml
        proxy_pass http://backend-service:8080/api/;
        
        # Przekazanie nagłówków (standardowa procedura)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}